export default {
    name: 'root',
    status: 0,
    children: [{
        name: 'nanjing',
        status: 2,
        children: [{
            name: '2-1-1',
            status: 3,
            children: [] 
        }, {
            name: '2-1-2',
            status: 3,
            children: [] 
        }, {
            name: '2-1-3',
            status: 3,
            children: [] 
        }, {
            name: '2-1-4',
            status: 3,
            children: [] 
        }, {
            name: '2-1-5',
            status: 3,
            children: [] 
        }, {
            name: '2-1-1',
            status: 3,
            children: [] 
        }, {
            name: '2-1-2',
            status: 3,
            children: [] 
        }, {
            name: '2-1-3',
            status: 3,
            children: [] 
        }, {
            name: '2-1-4',
            status: 3,
            children: [] 
        }, {
            name: '2-1-5',
            status: 3,
            children: [] 
        }]
    }]
};